project:
  type: website
website:
  title: "Curso LaTeX Grado Matem치ticas UGR"
  search: false
  repo-url: https://github.com/latex-mat-ugr/Curso-LaTeX
  navbar:
    right:
      - icon: github
        href: https://github.com/latex-mat-ugr/Curso-LaTeX
        aria-label: GitHub

  sidebar: 
    style: "docked"
    footer: Hecho con [Quarto](https://quarto.org/)
    contents:
      - text: "Documento b치sico"
        href: Documento sencillo/about.qmd
      - text: "Matem치ticas"
        href: Matematicas/about.qmd
      - text: "Transparencias beamer"
        href: Beamer/about.qmd
      - text: "Markdown"
        href: Markdown/about.qmd
      - text: "Personalizaci칩n"
        href: Personalizacion/about.qmd

format:
  html:
    theme: cosmo
    toc: true



